-- MySQL Script generated by MySQL Workbench
-- 01/21/15 10:40:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema employee_management_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  `department_id` INT NOT NULL,
  `name` VARCHAR(25) NULL,
  `hod` VARCHAR(9) NULL,
  INDEX `fk_Department_Employee_idx` (`hod` ASC),
  PRIMARY KEY (`department_id`),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_Department_Employee`
    FOREIGN KEY (`hod`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employment_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employment_status` ;

CREATE TABLE IF NOT EXISTS `employment_status` (
  `employment_status_id` INT NOT NULL,
  `employment_status` VARCHAR(25) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`employment_status_id`),
  UNIQUE INDEX `idEmploymentStatus_UNIQUE` (`employment_status_id` ASC),
  UNIQUE INDEX `EmploymentStatus_UNIQUE` (`employment_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employee_salary`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee_salary` ;

CREATE TABLE IF NOT EXISTS `employee_salary` (
  `salary_id` INT NOT NULL,
  `basic_salary` INT NOT NULL,
  `bonus` INT NULL,
  `benefit_total` INT NULL,
  `total_amount` INT NOT NULL,
  PRIMARY KEY (`salary_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `designation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `designation` ;

CREATE TABLE IF NOT EXISTS `designation` (
  `designation_id` INT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`designation_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee` ;

CREATE TABLE IF NOT EXISTS `employee` (
  `employee_id` VARCHAR(9) NOT NULL,
  `first_name` VARCHAR(15) NOT NULL,
  `mid_name` VARCHAR(15) NULL,
  `last_name` VARCHAR(15) NULL,
  `address` VARCHAR(45) NULL,
  `phone_no` BIGINT(10) NULL,
  `salary_id` INT NULL,
  `supervisor_id` VARCHAR(9) NULL,
  `department_id` INT NULL,
  `employment_status_id` INT NULL,
  `gender` ENUM('M','F') NOT NULL,
  `designation_id` INT NULL,
  PRIMARY KEY (`employee_id`),
  
  INDEX `fk_Employee_Department1_idx` (`department_id` ASC),
  INDEX `fk_Employee_EmploymentStatus1_idx` (`employment_status_id` ASC),
  INDEX `fk_employee_employee_salary1_idx` (`salary_id` ASC),
  INDEX `fk_employee_designation1_idx` (`designation_id` ASC),
  
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `department` (`department_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_EmploymentStatus1`
    FOREIGN KEY (`employment_status_id`)
    REFERENCES `employment_status` (`employment_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_employee_salary1`
    FOREIGN KEY (`salary_id`)
    REFERENCES `employee_salary` (`salary_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employee_designation1`
    FOREIGN KEY (`designation_id`)
    REFERENCES `designation` (`designation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `benefit` ;

CREATE TABLE IF NOT EXISTS `benefit` (
  `benefit_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`benefit_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employee_benefit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `employee_benefit` ;

CREATE TABLE IF NOT EXISTS `employee_benefit` (
  `employee_employeeId` VARCHAR(9) NOT NULL,
  `benefit_id` INT NOT NULL,
  PRIMARY KEY (`employee_employeeId`, `benefit_id`),
  INDEX `fk_employee_has_benefits_benefits1_idx` (`benefit_id` ASC),
  INDEX `fk_employee_has_benefits_employee1_idx` (`employee_employeeId` ASC),
  CONSTRAINT `fk_employee_has_benefits_employee1`
    FOREIGN KEY (`employee_employeeId`)
    REFERENCES `employee` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_has_benefits_benefits1`
    FOREIGN KEY (`benefit_id`)
    REFERENCES `benefit` (`benefit_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

ALTER TABLE `employee` add CONSTRAINT fk_employee_employee1 FOREIGN KEY (supervisor_id) 
REFERENCES employee (employee_id) ON UPDATE CASCADE ON DELETE SET NULL;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
