-- MySQL Script generated by MySQL Workbench
-- 01/20/15 04:57:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `DId` INT NOT NULL,
  `Name` VARCHAR(25) NULL,
  `HOD` VARCHAR(9) NULL,
  INDEX `fk_Department_Employee_idx` (`HOD` ASC),
  PRIMARY KEY (`DId`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC),
  CONSTRAINT `fk_Department_Employee`
    FOREIGN KEY (`HOD`)
    REFERENCES `mydb`.`Employee` (`EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EmploymentStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EmploymentStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EmploymentStatus` (
  `id` INT NOT NULL,
  `EmploymentStatus` VARCHAR(25) NOT NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idEmploymentStatus_UNIQUE` (`id` ASC),
  UNIQUE INDEX `EmploymentStatus_UNIQUE` (`EmploymentStatus` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Designation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Designation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Designation` (
  `Title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Title`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `EmployeeId` VARCHAR(9) NOT NULL,
  `FName` VARCHAR(15) NOT NULL,
  `MName` VARCHAR(15) NULL,
  `LName` VARCHAR(15) NULL,
  `Address` VARCHAR(45) NULL,
  `PhoneNo` INT(10) NULL,
  `Salary` INT NULL,
  `Designation` INT NULL,
  `SuperVisor` VARCHAR(9) NULL,
  `Department` INT NULL,
  `Status` VARCHAR(45) NULL,
  PRIMARY KEY (`EmployeeId`),
  INDEX `fk_Employee_Employee1_idx` (`SuperVisor` ASC, `EmployeeId` ASC),
  INDEX `fk_Employee_Department1_idx` (`Department` ASC),
  INDEX `fk_Employee_EmploymentStatus1_idx` (`Status` ASC),
  INDEX `fk_Employee_Designation1_idx` (`Designation` ASC),
  CONSTRAINT `fk_Employee_Employee1`
    FOREIGN KEY (`SuperVisor` , `EmployeeId`)
    REFERENCES `mydb`.`Employee` (`EmployeeId` , `EmployeeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Department1`
    FOREIGN KEY (`Department`)
    REFERENCES `mydb`.`Department` (`DId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_EmploymentStatus1`
    FOREIGN KEY (`Status`)
    REFERENCES `mydb`.`EmploymentStatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_Designation1`
    FOREIGN KEY (`Designation`)
    REFERENCES `mydb`.`Designation` (`Title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
